export const GET_WEATHER = 'GET_WEATHER'
export const SET_WEATHER_LOADING = 'SET_WEATHER_LOADING'
export const SET_WEATHER_ERROR = 'SET_WEATHER_ERROR'
export const SET_WEATHER_CITY = 'SET_WEATHER_CITY'
